name: stable-builder

on:
  workflow_dispatch:
  push:

env:
  ROS_DISTRO: humble

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      DEB_DISTRO: jammy
    steps:
      - name: ROS buildfarm
        uses: jspricke/ros-deb-builder-action@main
        with:
          DEB_DISTRO: ${{ env.DEB_DISTRO }}
          ROS_DISTRO: ${{ env.ROS_DISTRO }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SBUILD_CONF: |
            $enable_network = 1;
          SQUASH_HISTORY: true
          REPOS_FILE: sources.repos
          PACKAGES_BRANCH: stable
